version: "3"
services:
  webprod:
    build: .
    container_name: oauth-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    links:
      - mongo 
    volumes: 
      - ~/container-data-prod/images:/data
    environment:
      - DATABASE=mongodb://mongo:27017/puraprod
      - UPLOAD_PATH=/data
    networks:
      - app-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
